apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vvuz1kld4-go
  janus-idp.io/tekton: vvuz1kld4-go
  backstage.io/kubernetes-id: vvuz1kld4-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vvuz1kld4-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
