apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vvuz1kld4-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:bc7915e2c247386cee11edaaa6d142de22f24436@sha256:8e4bef20e3bcdfb198f01a224bae4303908a3ee460b8261d203d94a78b8bb389
          name: container-image
